config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :jobs
  resources :admin, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :pictures

  def save_images!(images)
    images.each do |image|
      self.pictures.create(title: "Untitled", description: "Add your description here!", image: image)
    end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :job
  has_attached_file :image,
  styles: { medium: "300x300>",
  thumb: "100x100>" },
  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :email
  has_many :jobs

  def is_admin?
    admin
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_is_admin!
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def edit
  end

  def new
    @user = current_user.users.new
  end

  def create
    @user = current_user.new(user_params)
    if @user.save
      redirect_to admin_index_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirct_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def ensure_is_admin!
    unless current_user.is_admin?
      flash[:error] = "You must be an admin to access this section"
      redirect_to root_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, except: [:index, :new, :create]

def index
  @jobs = Job.all
  @jobs = Job.paginate(page: params[:page], per_page: 12)
end

def show
end

def new
  @job = current_user.jobs.new
end

def create
  @job = current_user.jobs.new(job_params)
  if @job.save
    @job.save_images!(params[:images]) if params[:images].present?
    flash[:success] = 'Job created successfully!'
    redirect_to root_path(@job)
  else
    flash[:error] = 'Something went wrong!'
    render :new
  end
end

def edit
end

def update
  if @job.update(job_params)
    redirect_to root_path(@job), success: 'Job edited successfully!'
  else
    render :edit, error: 'Something went wrong!'
  end
end

def destroy
  if current_user.id != @job.user_id
    flash[:error] = "You are not the creator of that job so you can't delete it."
    redirect_to root_path
  else
  	@job.destroy
  	redirect_to root_path
  end
end

private
  def job_params
    params.require(:job).permit(:title, :date_created, :bio, :employee_creator, :materials_needed)
  end

  def set_job
    @job = Job.find(params[:id])
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/admin/_form.html.erb
<%= form_for @users do |f| %>
  <%= f.label :email %>
  <%= f.email :email %>
  
  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>

  <%= f.submit nil, class: 'btn blue' %>
<% end %>

app/views/admin/index.html.erb
<h1>Admin Panel</h1>
<div>
  <ul>
    <% @users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
  </ul>
</div>
<div>
  
</div>

app/views/jobs/_form.html.erb
<div class="row">
    <%= form_for @job, html: { multipart: true } do |f| %>
      <div class="row">
        <div class="input-field col s12 m6 l4">
          <%= f.text_field :title %>
          <%= f.label :title %>
        </div>
        <div class="input-field col s12 m6 l4">
          <%= f.date_field :date_created %>
          <%= f.label :date_created, class: 'active' %>
        </div>
        <div class="input-field col s12 m6 l4">
          <%= f.text_field :materials_needed %>
          <%= f.label :materials_needed %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m6 l4">
          <%= f.text_area :bio %>
          <%= f.label :bio %>
        </div>
        <div class="input-field col s12 m6 l4">
          <%= f.text_field :employee_creator %>
          <%= f.label :employee_creator %>
        </div>
        <div class="input-field col s12 m6 l4 btn">
          <%= file_field_tag "images[]", type: :file, multiple: true %>
        </div>
      </div>
      <div class="row center">
        <%= f.submit nil, class: 'btn blue' %>
      </div>
   <% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render(partial: 'form') %>

app/views/jobs/index.html.erb
<div class='row'>
  <% if @jobs.any? %>
    <% @jobs.order('created_at DESC').each do |job| %>
      <div class='col s12 m6 l3 center'>
        <h3><%= job.title %></h3>
        <div>
          <%= link_to 'Show', job_path(job), class: 'btn' %>
        </div>
      </div>
      <% end %>
  <% else %>
    <h3>No Jobs, Please Create One!</h3>
  <% end %>
</div>
<br />
<div class='row center'>
  <%= will_paginate @jobs %>
</div>

app/views/jobs/new.html.erb
<h1 class='center'>New Job</h1>

<%= render(partial: 'form') %>

app/views/jobs/show.html.erb
<div class='row'>
  <h1 class='center'><%= @job.title %></h1>
</div>
<hr />
<div class='row'>
  <div class='col s12 m6 l6 center'>
    <h6>Created By: <%= @job.employee_creator %></h6>
    <h5><%= @job.date_created %></h5>
  </div>
  <div class='col s12 m6 l6 center'>
    <h6>Notes: <%= @job.bio %></h6>
    <br />
    <h6>Materials: <%= @job.materials_needed %></h6>
  </div>
</div>

<% @job.pictures.each do |picture| %>
  <%= image_tag picture.image.url(:medium) %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper black">
    <a href="/"><img id='lable' src="<%= asset_path('pic.jpg') %>"</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse">
      <i class="material-icons">menu</i>
    </a>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "New", new_job_path %></li>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <% if current_user.is_admin? %>
          <li><%= link_to "Admin", admin_index_path %> </li>
        <% end %>
        <li id='nav'><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li id='nav'><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <% if user_signed_in? %>
        <li><%= link_to "New", new_job_path %></li>
          <li><%= link_to 'Account', edit_user_registration_path %></li></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% if current_user.is_admin? %>
            <li><%= link_to "Admin", admin_index_path %></li>
          <% end %>
        <% else %>
          <li id='nav'><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datadump</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render(partial: 'layouts/navbar') %>
    <div class='center green lighten-3 close'>
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <div class="container">
        <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  </body>
</html>